#!/usr/bin/env bash
# EDA Playground has no folders, and it only compiles design.sv and
# testbench.sv. This copies every TB file flat into sim/edaplayground/,
# drops the DUT in as design.sv, and generates a testbench.sv that
# `includes the top-level files in tb.f order. Upload everything in that folder.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/sim/edaplayground"
DUT="pcie_axil_master_minimal.v"

# flat copy only works if no two files share a basename
dups=$(find "$ROOT/tb" -name '*.sv' -exec basename {} \; | sort | uniq -d)
if [ -n "$dups" ]; then
  echo "duplicate file names under tb/, can't flatten: $dups" >&2
  exit 1
fi

rm -rf "$OUT"
mkdir -p "$OUT"
find "$ROOT/tb" -name '*.sv' -exec cp {} "$OUT/" \;

{
  echo "// generated by sim/flatten_for_edaplayground.sh from sim/tb.f -- don't edit"
  grep -Ev '^[[:space:]]*(//|\+|$)' "$ROOT/sim/tb.f" | while read -r f; do
    b=$(basename "$f")
    if [ "$b" = "$DUT" ]; then
      cp "$ROOT/$f" "$OUT/design.sv"
    else
      echo "\`include \"$b\""
    fi
  done
} > "$OUT/testbench.sv"

echo "wrote $(ls "$OUT" | wc -l | tr -d ' ') files to $OUT"
